### ISSUE TITLE
Documentation: graph-sync-job -> middletier Namespace or Backend Namespace

### ISSUE THREAD

**Issue by VannTen** [thoth-station/adviser#2361]
In `docs/source/architecture.rst`, graph-sync is mentionned as running in two
namespaces: 

```
Middletier Namespace
####################

... 

* `graph-sync-job <https://github.com/thoth-station/graph-sync-job>`__ - a job
  responsible for syncing data in a JSON format persisted on Ceph to the Thoth's
  knowledge graph database

...
Backend Namespace
#################

...

* `graph-sync-job <https://github.com/thoth-station/graph-sync-job>`__ - a job
  responsible for syncing data in a JSON format persisted on Ceph to the Thoth's
  knowledge graph database
```

(lines 135 and 172)

Which one is it ? (unless it runs in both ?)

/kind documentation

**Comment by harshad16** [comment]
It is a workflow that executes across multiple namespaces. It is responsible for syncing the workload result to the postgresql database, so that is the reason why it is available in multiple namespaces. 
For example: 
Adviser executes on backend and solver executes on middletier. The graph-sync would sync the respective component after their execution to postgresql database, for this process to take place the graph-sync uses the same namespace.

can you share at which part it would have been helpful to have this information ? i would update this there.

**Comment by VannTen** [comment]
I think maybe just a reference (on each of the occurence) to and
end-of-page note stating just that would be fine.
